### ISSUE TITLE
Issue while creating PV that binds to PVC

### ISSUE THREAD

**Issue by limbuu** [A4ANK/EKS_K8s_cluster_on_aws_efs_provisioning_pvc#1]
Name:          efs-mysql
Namespace:     default
StorageClass:  aws-efs
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-class: aws-efs
               volume.beta.kubernetes.io/storage-provisioner: aws-efs-provisioner
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Mounted By:    <none>
Events:
  Type    Reason                Age               From                         Message
  ----    ------                ----              ----                         -------
  Normal  ExternalProvisioning  5s (x4 over 45s)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "aws-efs-provisioner" or manually created by system administrator

**Comment by limbuu** [comment]
I couldn't solve this issue, is there any way to fix this?

**Comment by A4ANK** [comment]
First, create a service account and storage class for creating PVs dynamically using storage classes, and then request for PV using PVC. This how you might be able to resolve this issue. 

So if you are using a self-managed K8s cluster then follow these steps to create K8s resources in the order given below.
1. create a service account.| and which has role-based access controls.
2. create an external provisioner.
3. create a storage class.
4. Now, you can claim for PV using PVC with the same storage-class name that you have created earlier.

And if you're using a Fargate cluster, which is a managed service from AWS, then you should read AWS documentation for this:-
=> Currently there is no support for stateful workloads that require persistent volumes or file systems.
https://aws.amazon.com/blogs/aws/amazon-eks-on-aws-fargate-now-generally-available/
